apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:oemvTqrSxhY9ELJGWw3qpcVyvIa/H6ZQROhLhZw0pNfDGpI2khk271ktetO5VeTC4ZDWB6r4rkAQ9ntgMq/emHv+tUs2MTsfNNt04BlqSQJKxz4ReWBBHkibSYJJZSb6MNVKOwJQTQK6g/iVgAAkgSpqTti4NhBz/mh1oG1ZIhcIB1NEOZgDm2Tp+sltpTL9Urr98G/Tb6xPKYhWVRWQ2LYQM32eOx2p5ElN+NtrlgYDy5ihTTA5Yy7sVv8X2nQjDeTYSR1TPdRnpOmUQsGBQfGFZtV5Y2Pgi/Sg6SWkBBA4Bv7N2ceCfUSKjB4P87NcQmcv9kzQw3Cm8/jyvt9ycA==,iv:xEvOIiA5Bz4QAUaVSSM0UjyatpEUosJ38FFAOeIOFxo=,tag:tA4eDfHldqKJsQX80tzeZQ==,type:str]
kind: Secret
metadata:
    name: sops-age
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWRHSXExMW5QNGN2elJs
            QzVvVTRTRFp6SjFBcmJOTHhlZUtQV3VrSmxvCkxQWTNBR2o4VVRDVFpSSWlrWEpa
            eVUwVnQ0MmEwY3ZYMjdVOEFWWWx0SFkKLS0tIHk5d2xGWDI0VkVOMCtsai9WMStp
            ZFNlbEt3bUV6QWQrZER6UFI4djhNd3cKJvJjRPLZso35a9FgarV752nTSls5LEjJ
            zX69ckaUB4yOyVlf/q0FvsVPeHN2q2TB6hdtGCohMzjJLe8glova+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T14:02:27Z"
    mac: ENC[AES256_GCM,data:LE9/FzU0wexRQiB4aeCGU+Npf+JlZyjN15W6ZanSpLJPlpdMHJ68aMKewu7QQ0SKMppwff0+OTSydf0ZJ0C1Any+7Zb83i4P+v04jIGGezK96dvHktSC+paw1gg+28npRkr3mYoBgqellKzE8z6ZEQGjtL9CtlfNdfEtaPCF+rU=,iv:VEXHu2dDrv7CcPE9PGw68fa7douw4bZI9oH4SzOfr4I=,tag:PGPd2R7BUXYKLd3nK8fQGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
