---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: koffan
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        APP_PASSWORD: "{{ .KOFFAN_APP_PASSWORD }}"
        API_TOKEN: "{{ .KOFFAN_API_TOKEN }}"
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: koffan
