---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
        GARAGE_METRICS_TOKEN: "{{ .GARAGE_METRICS_TOKEN }}"
        GARAGE_WEBUI_AUTH_USER_PASS: "{{ .GARAGE_WEBUI_AUTH_USER_PASS }}"
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: garage
