---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - garagecluster.yaml
  - garagekey.yaml
  - garagereferencegrant.yaml
  - sneaker-social.yaml
  - referencegrant.yaml
