---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
  namespace: flux-system
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        token: |-
          {{ .FLUXRECEIVER_GITHUB_TOKEN }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: flux-receiver
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-webhook-secret
  namespace: flux-system
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        token: |-
          {{ .FLUXRECEIVER_FORGEJO_TOKEN }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: flux-receiver
