---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-initdb
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRES_SUPERUSER_PASSWORD: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}

        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .CODER_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .CODER_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .CODER_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: postgresql
    - extract:
        key: coder
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: authentik-oauth
  target:
    template:
      data:
        CODER_OIDC_IGNORE_EMAIL_VERIFIED: "true"
        CODER_OIDC_SIGN_IN_TEXT: "Wynning SSO"
        CODER_OIDC_ISSUER_URL: |-
          https://auth.${SECRET_ROOT_DOMAIN}/application/o/coder/
        CODER_OIDC_CLIENT_ID: "{{ .client_id }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: Coder
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CODER_PG_CONNECTION_URL: |-
          postgres://{{ .CODER_POSTGRES_USERNAME }}:{{ .CODER_POSTGRES_PASSWORD }}@${SVC_POSTGRES_HOST}/{{ .CODER_POSTGRES_DATABASE }}

        # CODER_OIDC_ISSUER_URL: |-
        #   {{ .CODER_OIDC_ISSUER_URL }}
        CODER_OIDC_EMAIL_DOMAIN: |-
          {{ .CODER_OIDC_EMAIL_DOMAIN }}
        # CODER_OIDC_CLIENT_ID: |-
        #   {{ .CODER_OIDC_CLIENT_ID }}
        # CODER_OIDC_CLIENT_SECRET: |-
        #   {{ .CODER_OIDC_CLIENT_SECRET }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: coder
