---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: cloudnative-pg-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .POSTGRES_SUPERUSER_USERNAME }}
        password: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: postgresql
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-minio
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: postgres-minio
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MINIO_ACCESS_KEY: |-
          {{ .POSTGRESQL_MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: |-
          {{ .POSTGRESQL_MINIO_SECRET_KEY }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: postgresql-minio
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-garage
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: postgresql-garage
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GARAGE_REGION: garage
        GARAGE_ACCESS_KEY: |-
          {{ .POSTGRESQL_GARAGE_ACCESS_KEY }}
        GARAGE_SECRET_KEY: |-
          {{ .POSTGRESQL_GARAGE_SECRET_KEY }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: postgresql-garage
