---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shlink
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GEOLITE_LICENSE_KEY: "{{ .SHLINK_GEOLITE_LICENSE_KEY }}"
        INITIAL_API_KEY: "{{ .SHLINK_API_KEY }}"
        SHLINK_SERVER_API_KEY: "{{ .SHLINK_API_KEY }}"

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: shlink
