---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: longhorn-system
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AWS_ENDPOINTS: |-
          https://${SECRET_MINIO_URL}:9443
        AWS_ACCESS_KEY_ID: |-
          {{ .LONGHORN_MINIO_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .LONGHORN_MINIO_SECRET_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: longhorn
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-oidc
  namespace: longhorn-system
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        client-secret: |-
          {{ .LONGHORN_OIDC_CLIENT_SECRET }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: longhorn
