---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - cilium/ks.yaml
  - descheduler/ks.yaml
  - intel-gpu-plugin/ks.yaml
  - keda/ks.yaml
  - kube-vip/ks.yaml
  - kured/ks.yaml
  - local-path-provisioner/ks.yaml
  - node-feature-discovery/ks.yaml
  - ocharted/ks.yaml
  - reloader/ks.yaml
  - snapshot-controller/ks.yaml
components:
  - ../../components/common
  - ../../components/cluster-vars
  - ../../components/limits
