---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ATUIN_DB_URI: |-
          postgresql://{{ .ATUIN_POSTGRES_USERNAME }}:{{ .ATUIN_POSTGRES_PASSWORD }}@${SVC_POSTGRES_HOST}:${SVC_POSTGRES_PORT}/{{ .ATUIN_POSTGRES_DATABASE }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: atuin
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-init-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .ATUIN_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .ATUIN_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .ATUIN_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: atuin
    - extract:
        key: postgresql
