---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plausible
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DATABASE_URL: postgres://{{ .PLAUSIBLE_POSTGRES_USERNAME }}:{{ .PLAUSIBLE_POSTGRES_PASSWORD }}@${SVC_POSTGRES_HOST}:5432/{{ .PLAUSIBLE_POSTGRES_DATABASE }}

        SECRET_KEY_BASE: |-
          {{ .PLAUSIBLE_SECRET_KEY_BASE }}
        TOTP_VAULT_KEY: |-
          {{ .PLAUSIBLE_TOTP_VAULT_KEY }}

        GEOIPUPDATE_ACCOUNT_ID: |-
          {{ .GEOIPUPDATE_ACCOUNT_ID }}
        GEOIPUPDATE_LICENSE_KEY: |-
          {{ .GEOIPUPDATE_LICENSE_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: plausible
    - extract:
        key: geoipupdate
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plausible-initdb
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .PLAUSIBLE_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .PLAUSIBLE_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .PLAUSIBLE_POSTGRES_PASSWORD }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: plausible
    - extract:
        key: postgresql
