apiVersion: v1
kind: Secret
metadata:
    name: bw-secrets
type: Opaque
stringData:
    BW_ORG_ID: ENC[AES256_GCM,data:WBdlhQzN79qs7LmY9VaUhSvNFNT1IQzb/PnG/jNsLMqDahrZ,iv:GN+w9YMHieZxk/csdHDL3m6pRqE05sEMLAYsRpFHNuY=,tag:Kg9Q9Vel++K2BXe4MCuXTw==,type:str]
    BW_PROJECT_ID: ENC[AES256_GCM,data:npOTVj6E6ebJGyQlnrmvUy0SBSDwgLVRitgb22W6fu+VabMs,iv:rV+qPfNtyZJ+vO8Hruw8sPJU9pchI88KKAu9LL/LaSM=,tag:OQAH5SzrWG/8E636/U/Ung==,type:str]
    BW_PROJECT_TOKEN: ENC[AES256_GCM,data:EaSI59JPD3Ob4o7QFHYUoRU08l+cTToteUCijkJPkoofpxVt1r+Rp1vgZOgdsHtol3029qdpWcq9aQ7sT5yy2Q4oE/mwvB+SK1v1Ud2ud+lLLW4NF4UfCToqEwlsSg==,iv:+MZ8soAWGoe8P7bC8H1t45VoccwXbMZ/jbxys1E89ak=,tag:Iaec3pn+9PD5Lo/OEGRSTw==,type:str]
sops:
    age:
        - recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSlBtNmx2TEtmZGZVQ3NF
            MnhTZXZPazZURWpRKytIRTM2c2RxbTNlRnpRCmxIZjl0OXh6Z2NhRk1rTERkU0cr
            bkNiWkhWVThCU0s5SmdKdHkyUGhMZUkKLS0tIGp5VktZdWZsa3hDd1FpcElUeCtk
            ZllPMHQrdFUxUlJpUlFiWFdRSGthNXcKopSbZ96Bbc8nidBLG0jTJk9IGy0/Eihe
            ZSmGdGBDXpLvJ8ExTIIVieHf8A9bwQMyQ2YDxU4j62aBxPcm2Nlcgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T20:31:15Z"
    mac: ENC[AES256_GCM,data:099IMy1J+kSveSHqFzZ552bjFKYcad5t9wX/H75zrPxtltx8WJ09H21w/HXdYHt6t7sehrBZ0B+xCr15quLsZQJ3GIDes/8BX4biUha8OUx9Ggogu4VP6a56i3F3fdZ6bGBM1QOmy6pyjtcWeFq6iLokzWMkxnVgYRHoYpiiRtU=,iv:c4OCv40a453ISLVSUyAb5XIvLx3oe+sRHSUiPdT50gw=,tag:iXkgF67r7G7aUKjsIW7Qsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    labels:
        external-secrets.io/type: webhook
type: Opaque
stringData:
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ZFUAcy34kKx4b56JPfEDbcM8Nll6BR061uOMHjDlH8x7pgNd3+QzGb0JjBZHhsff7XTZBG1u8+e6RzWm,iv:rAw7oTUYAaoKXxCJsPnORwAGKNaaZ9qyiEC5hotht98=,tag:elHbXASaWJkx5QO9nmNujg==,type:str]
sops:
    age:
        - recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSlBtNmx2TEtmZGZVQ3NF
            MnhTZXZPazZURWpRKytIRTM2c2RxbTNlRnpRCmxIZjl0OXh6Z2NhRk1rTERkU0cr
            bkNiWkhWVThCU0s5SmdKdHkyUGhMZUkKLS0tIGp5VktZdWZsa3hDd1FpcElUeCtk
            ZllPMHQrdFUxUlJpUlFiWFdRSGthNXcKopSbZ96Bbc8nidBLG0jTJk9IGy0/Eihe
            ZSmGdGBDXpLvJ8ExTIIVieHf8A9bwQMyQ2YDxU4j62aBxPcm2Nlcgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T20:31:15Z"
    mac: ENC[AES256_GCM,data:099IMy1J+kSveSHqFzZ552bjFKYcad5t9wX/H75zrPxtltx8WJ09H21w/HXdYHt6t7sehrBZ0B+xCr15quLsZQJ3GIDes/8BX4biUha8OUx9Ggogu4VP6a56i3F3fdZ6bGBM1QOmy6pyjtcWeFq6iLokzWMkxnVgYRHoYpiiRtU=,iv:c4OCv40a453ISLVSUyAb5XIvLx3oe+sRHSUiPdT50gw=,tag:iXkgF67r7G7aUKjsIW7Qsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
