---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-init-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .__APP_UPPER___POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .__APP_UPPER___POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .__APP_UPPER___POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    # TODO: ensure these Bitwarden keys exist (the app's own key + the shared `postgresql` key).
    - extract:
        key: __APP__
    - extract:
        key: postgresql
