---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app echo-server
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: *namespace
  components:
    # - ../../../../components/forward-auth
    - ../../../../components/db-scaler
  postBuild:
    substitute:
      APP: *app
      AUTH_ROUTE: *app
      DB_SCALAR_THRESHOLD: "4"
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./apps/default/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
