---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: ntfy-alertmanager
    namespace: monitoring
spec:
    secretStoreRef:
        name: bitwarden-secrets-manager-sdk
        kind: ClusterSecretStore
    target:
        deletionPolicy: Delete
        template:
            type: Opaque
            data:
                config.scfg: |-
                    base-url https://ntfy-alertmanager.${SECRET_ROOT_DOMAIN}
                    http-address :8080
                    log-level debug
                    log-format text
                    alert-mode single

                    user {{ .NTFY_ALERTMANAGER_USERNAME }}
                    password {{ .NTFY_ALERTMANAGER_PASSWORD }}

                    labels {
                        order "severity"

                        severity "critical" {
                            priority 4
                            tags "rotating_light"
                            # icon "https://example.com/critical.png"
                            # Forward messages which severity "critical" to the specified email address.
                            #email-address foo@example.com
                            # Call the specified number. Use `yes` to pick the first of your verified numbers.
                            #call yes
                        }

                        severity "warning" {
                            priority 3
                        }

                        severity "info" {
                            priority 1
                        }

                        # instance "example.com" {
                        #     topic homeserver
                        #     tags "computer,example"
                        # }
                    }

                    # Settings for resolved alerts
                    resolved {
                        tags "resolved,partying_face"
                        # icon "https://example.com/resolved.png"
                        priority 1
                        update-notification true
                    }

                    ntfy {
                        server https://ntfy.${SECRET_ROOT_DOMAIN}
                        topic prometheus
                        access-token {{ .NTFY_ALERTMANAGER_TOKEN }}
                    }

                    alertmanager {
                        silence-duration 24h
                        url https://prom-alert.${SECRET_INTERNAL_DOMAIN}
                    }

                    cache {
                        # The type of cache that will be used
                        # Options: disabled, memory, redis
                        # Default: disabled
                        type memory
                        # How long messages stay in the cache for
                        # Default: 24h
                        duration 24h

                        # Memory cache settings
                        # Interval in which the cache is cleaned up
                        # Default: 1h
                        cleanup-interval 1h

                        # Redis cache settings
                        # URL to connect to redis (default: redis://localhost:6379)
                        # Default: redis://localhost:6379
                        #redis-url redis://user:password@localhost:6789/3
                    }

    refreshInterval: 15m
    dataFrom:
        - extract:
              key: ntfy-alertmanager
