---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: endurain-initdb
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .ENDURAIN_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .ENDURAIN_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .ENDURAIN_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: endurain
    - extract:
        key: postgresql
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: endurain
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DB_TYPE: postgres
        DB_HOST: "${SVC_POSTGRES_HOST}"
        # DB_PORT: "${SVC_POSTGRES_PORT}"
        DB_USER: |-
          {{ .ENDURAIN_POSTGRES_USERNAME }}
        DB_PASSWORD: |-
          {{ .ENDURAIN_POSTGRES_PASSWORD }}
        DB_DATABASE: |-
          {{ .ENDURAIN_POSTGRES_DATABASE }}
        SECRET_KEY: |-
          {{ .ENDURAIN_SECRET_KEY }}
        FERNET_KEY: |-
          {{ .ENDURAIN_FERNET_KEY }}

        GEOCODES_MAPS_API: |-
          {{ .GEOCODE_MAP_APIKEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: endurain
    - extract:
        key: geocodes
