---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-minio
  namespace: office
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: immich-postgres-minio
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        minio_access_key: |-
          {{ .IMMICH_POSTGRES_MINIO_ACCESS_KEY }}
        minio_secret_key: |-
          {{ .IMMICH_POSTGRES_MINIO_SECRET_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: immich
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-garage
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: postgresql-garage
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GARAGE_REGION: garage
        GARAGE_ACCESS_KEY: |-
          {{ .POSTGRESQL_GARAGE_ACCESS_KEY }}
        GARAGE_SECRET_KEY: |-
          {{ .POSTGRESQL_GARAGE_SECRET_KEY }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: postgresql-garage
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-superuser
  namespace: office
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: immich-postgres-superuser
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: |-
          {{ .IMMICH_POSTGRES_USERNAME }}
        password: |-
          {{ .IMMICH_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: immich
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
  namespace: office
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: immich-postgres
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: |-
          {{ .IMMICH_POSTGRES_DATABASE_USERNAME }}
        password: |-
          {{ .IMMICH_POSTGRES_DATABASE_PASSWORD }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: immich
