---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud2
  namespace: office
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: nextcloud2-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .NEXTCLOUD_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .NEXTCLOUD_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .NEXTCLOUD_POSTGRES_PASSWORD }}

        NEXTCLOUD_ADMIN_USERNAME: |-
          {{ .NEXTCLOUD_ADMIN_USERNAME }}
        NEXTCLOUD_ADMIN_PASSWORD: |-
          {{ .NEXTCLOUD_ADMIN_PASSWORD }}
        NEXTCLOUD_REDIS_PASSWORD: |-
          {{ .NEXTCLOUD_REDIS_PASSWORD }}

        POSTGRES_DB: |-
          {{ .NEXTCLOUD_POSTGRES_DATABASE }}
        POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        POSTGRES_USER: |-
          {{ .NEXTCLOUD_POSTGRES_USERNAME }}
        POSTGRES_PASSWORD: |-
          {{ .NEXTCLOUD_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: postgresql
