---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  storageClassName: nextcloud-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NAS_URL}"
    path: /volume1/nextcloud
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: office
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 1Mi
