---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/garage.rajsingh.info/garagebucket_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: blog-int-wynning-tech
spec:
  clusterRef:
    name: garage-cluster
    namespace: default
  quotas:
    maxSize: 1Gi
  website:
    enabled: true
  globalAlias: blog.${SECRET_INTERNAL_DOMAIN}
