---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-forgejo
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-data-forgejo
