---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-todo
resources:
  - simple-todo/ks.yaml
components:
  - ../../components/common
  - ../../components/cluster-vars
  - ../../components/limits
  - ../../components/forgejo-docker-creds
