kind: Secret
apiVersion: v1
metadata:
    name: echo-server-oidc
    namespace: default
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:gRyohvFQBkB/jFlYO9/peHwGgX5rHeqeGNPgv/A+lQAJaRvTg1d4b0mGNtccWLZ0nt+T+T42onEE8lx1aNzZxD3IZi1XBDLGgscIjmarSZH7jKsyjgRGm77bcxrJVCqQMum4vz4jrlrs6vMdUITBfWpBMZfGjTm/0V41mo0WGHU=,iv:U7CavXY2Z+vk1+66ClSorzN6s6JBFDMed9kwkSkef9M=,tag:3BH/lz57z/Mx5FXeCt54cA==,type:str]
sops:
    age:
        - recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL1k0MkptWDQxRUVtSkho
            VVJvY0p1aGJzRWhaOEVXM2NGQXcwdTYyMmdVCk9IQXAwMTlOVTFFSlhjckVGaUhP
            cnVWdXk2OUxQK1pEWjIrSmtQaDJNbWsKLS0tIGhPeEtuSVVvclhpNTVycGZFc0Rv
            M0Q1MlpxRnhzTzNpRW9hbU85YU5mekUKlRV9n0li1j9LgQjDyde+2L97Qa/30E30
            eErgtpPg+elmFZGoXOPxUpebXHiH63mDFYSx5c28dq3V2xFFi6f2sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:57:11Z"
    mac: ENC[AES256_GCM,data:vVj6pUtHR3I+jfUFcZT9jIiGXmgNc0h7rNX/HhJxZnxq3IA55kTjBQvERfQ0AuputwB8k3rxMbNgt58qJ14IfHcU2dro7wqyFRszuGo8/CftS6b0IdDMx+3d7UpsBHDJxE2G05A34/2QIxEiFaQHRqSzIuRVm60H5k/CWScj22k=,iv:lPnUkZtJl8qfMWufbLntuRWjFlmZmUGMBKK4ZDNFJmk=,tag:oLKqoYwA//Ucbhg+/Tdm9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
