---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: |-
          {{ .GRAFANA_ADMIN_USERNAME }}
        admin-password: |-
          {{ .GRAFANA_ADMIN_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: grafana
