---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MEILI_MASTER_KEY: |-
          {{ .KARAKEEP_MEILI_MASTER_KEY }}
        NEXTAUTH_SECRET: |-
          {{ .KARAKEEP_NEXTAUTH_SECRET }}

        OAUTH_CLIENT_ID: |-
          {{ .KARAKEEP_AUTH_CLIENTID }}
        OAUTH_CLIENT_SECRET: |-
          {{ .KARAKEEP_AUTH_CLIENTSECRET }}

        OPENAI_API_KEY: |-
          {{ .KARAKEEP_OPENAI_API_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: karakeep
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-oauth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: authentik-oauth
  target:
    # name: oauth-secret
    template:
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: Provider for Karakeep
