---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/garage.rajsingh.info/garagereferencegrant_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: gotosocial
  namespace: default
spec:
  from:
    - kind: GarageBucket
      namespace: gotosocial
    - kind: GarageKey
      namespace: gotosocial
  to:
    - kind: GarageCluster
      name: garage-nas
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/garage.rajsingh.info/garagereferencegrant_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: renovate
  namespace: default
spec:
  from:
    - kind: GarageBucket
      namespace: renovate
    - kind: GarageKey
      namespace: renovate
  to:
    - kind: GarageCluster
      name: garage-nas
