---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gateway
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.7.2
  url: oci://ghcr.io/k8s-gateway/charts/k8s-gateway
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    fullnameOverride: k8s-gateway
    domain: "${SECRET_INTERNAL_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: "${SVC_K8S_GATEWAY_ADDR}"
      externalTrafficPolicy: Cluster
    watchedResources: [ "HTTPRoute", "Ingress", "Service" ]
