---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AGENTMEMORY_SECRET: |-
          {{ .AGENTMEMORY_SECRET }}
        ANTHROPIC_API_KEY: |-
          {{ .AGENTMEMORY_ANTHROPIC_API_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: agentmemory
