---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ADMIN_TOKEN: |-
          {{ .VAULTWARDEN_ADMIN_TOKEN }}

        DATABASE_URL: |-
          postgresql://{{ .VAULTWARDEN_POSTGRES_USERNAME }}:{{ .VAULTWARDEN_POSTGRES_PASS }}@${SVC_POSTGRES_HOST}/{{ .VAULTWARDEN_POSTGRES_DATABASE }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: vaultwarden
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-init-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .VAULTWARDEN_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .VAULTWARDEN_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .VAULTWARDEN_POSTGRES_PASS }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: vaultwarden
    - extract:
        key: postgresql
