---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotosocial
  namespace: comms
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GTS_STORAGE_S3_ACCESS_KEY: |-
          {{ .GTS_GARAGE_ACCESS_KEY }}
        GTS_STORAGE_S3_SECRET_KEY: |-
          {{ .GTS_GARAGE_SECRET_KEY }}
        GTS_STORAGE_S3_ENDPOINT: |-
          ${SECRET_GARAGE_URL}
        GTS_STORAGE_S3_BUCKET: |-
          {{ .GTS_S3_BUCKET }}

        GARAGE_ACCESS_KEY: |-
          {{ .GTS_GARAGE_ACCESS_KEY }}
        GARAGE_SECRET_KEY: |-
          {{ .GTS_GARAGE_SECRET_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: gotosocial
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotosocial-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: authentik-oauth
  target:
    template:
      data:
        GTS_OIDC_ENABLED: |-
          true
        GTS_OIDC_IDP_NAME: |-
          authentik
        GTS_OIDC_ISSUER: |-
          https://auth.${SECRET_ROOT_DOMAIN}/application/o/gotosocial/
        GTS_OIDC_CLIENT_ID: "{{ .client_id }}"
        GTS_OIDC_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: GoToSocial
