---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: comms
resources:
  - helm-release.yaml
  - externalsecret.yaml
  - pvc.yaml
  - envoypolicy.yaml
  - garage.yaml
configMapGenerator:
  - name: gotosocial-config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
