apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeName: pvc-84fae8db-e443-4b6c-b8f8-0ccb2dc5554b
