---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        BAUTH_USER: |-
          {{ .NTFY_ALERTMANAGER_USERNAME }}
        BAUTH_PASS: |-
          {{ .NTFY_ALERTMANAGER_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: ntfy-alertmanager
