---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
spec:
  staticConfigs:
    - targets:
        - ${SECRET_NAS_URL}:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: node
      replacement: nas
    - action: replace
      targetLabel: job
      replacement: node-exporter
