---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
  namespace: monitoring
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.yaml: |-
          metrics: true
          storage:
            type: sqlite
            path: /config/sqlite.db
            caching: true
          ui:
            title: Status | Gatus
            header: Status
          web:
            port: 8080
          alerting:
            ntfy:
              title: Gatus
              topic: gatus
              token: {{ .SECRET_GATUS_NTFY_TOKEN }}
              url: https://ntfy.${SECRET_ROOT_DOMAIN}
              priority: 3
              resolved-priority: 0
              default-alert:
                description: health-check failed
                send-on-resolved: true
                failure-threshold: 3
                success-threshold: 3
          connectivity:
            checker:
              target: 1.1.1.1:53
              interval: 1m
          endpoints:
            - name: Cloudflare
              group: connectivity
              url: icmp://1.1.1.1
              interval: 1m
              conditions:
                - "[CONNECTED] == true"

            - name: helheim
              group: Nodes
              url: icmp://helheim.${SECRET_CORE_DOMAIN}
              interval: 1m
              alerts:
                - type: ntfy
              client:
                dns-resolver: tcp://192.168.1.1:53
              conditions:
                - "[CONNECTED] == true"
                - "[IP] == 192.168.1.15"

            - name: svartalfheim
              group: Nodes
              url: icmp://svartalfheim.${SECRET_CORE_DOMAIN}
              interval: 1m
              alerts:
                - type: ntfy
              client:
                dns-resolver: tcp://192.168.1.1:53
              conditions:
                - "[CONNECTED] == true"
                - "[IP] == 192.168.1.13"

            - name: muspelheim
              group: Nodes
              url: icmp://muspelheim.${SECRET_CORE_DOMAIN}
              interval: 1m
              alerts:
                - type: ntfy
              client:
                dns-resolver: tcp://192.168.1.1:53
              conditions:
                - "[CONNECTED] == true"
                - "[IP] == 192.168.1.12"

            - name: nidavellir
              group: Nodes
              url: icmp://nidavellir.${SECRET_CORE_DOMAIN}
              interval: 1m
              alerts:
                - type: ntfy
              client:
                dns-resolver: tcp://192.168.1.1:53
              conditions:
                - "[CONNECTED] == true"
                - "[IP] == 192.168.1.14"

            - name: niflheim
              group: Nodes
              url: icmp://niflheim.${SECRET_CORE_DOMAIN}
              interval: 1m
              alerts:
                - type: ntfy
              client:
                dns-resolver: tcp://192.168.1.1:53
              conditions:
                - "[CONNECTED] == true"
                - "[IP] == 192.168.1.18"

            - name: midgard
              group: Nodes
              url: icmp://midgard.dyn.${SECRET_ROOT_DOMAIN}
              interval: 1m
              alerts:
                - type: ntfy
              client:
                dns-resolver: tcp://192.168.1.1:53
              conditions:
                - "[CONNECTED] == true"
                - "[IP] == 10.10.2.2"

            # Doesn't seem able to connect to mqtt
            # - name: mqtt
            #   group: internal
            #   url: tcp://mqtt.${SECRET_INTERNAL_DOMAIN}
            #   interval: 1m
            #   alerts:
            #     - type: ntfy
            #   client:
            #     dns-resolver: tcp://192.168.1.1:1883
            #   conditions:
            #     - "[CONNECTED] == true"

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: gatus
