---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sneaker
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AUTH_CLIENT_ID: |-
          {{ .SNEAKER_AUTH_CLIENT_ID }}
        AUTH_CLIENT_SECRET: |-
          {{ .SNEAKER_AUTH_CLIENT_SECRET }}
        AUTH_ISSUER_URL: |-
          {{ .SNEAKER_AUTH_ISSUER_URL }}
        AUTH_INTROSPECTION_URL: |-
          {{ .SNEAKER_AUTH_INTROSPECTION_URL }}
        AUTH_TOKEN_URL: |-
          {{ .SNEAKER_AUTH_TOKEN_URL }}
        AUTH_SECRET: |-
          {{ .SNEAKER_AUTH_SECRET }}

        SNEAKER_DB_CONNECTION_STRING: |-
          postgresql://{{ .SNEAKER_POSTGRES_USERNAME }}:{{ .SNEAKER_POSTGRES_PASSWORD }}@${SVC_POSTGRES_HOST}:${SVC_POSTGRES_PORT}/{{ .SNEAKER_POSTGRES_DATABASE }}
        POSTGRES_DB_NAME: |-
          {{ .SNEAKER_POSTGRES_DATABASE }}
        POSTGRES_USER: |-
          {{ .SNEAKER_POSTGRES_USERNAME }}
        POSTGRES_PASSWORD: |-
          {{ .SNEAKER_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: sneaker-prod
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sneaker-init-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .SNEAKER_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .SNEAKER_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .SNEAKER_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: sneaker-prod
    - extract:
        key: postgresql
