---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sneaker-data
  namespace: sneaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
