---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-operator
  namespace: &namespace tailscale
spec:
  targetNamespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./apps/tailscale/tailscale-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-operator-config
  namespace: &namespace tailscale
spec:
  targetNamespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./apps/tailscale/tailscale-operator/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
