---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        client_id: |-
          {{ .TAILSCALE_OPERATOR_CLIENT_ID }}
        client_secret: |-
          {{ .TAILSCALE_OPERATOR_CLIENT_SECRET }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: tailscale-operator
