---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-backup
  namespace: minio
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MINIO_URL: |-
          https://${SECRET_MINIO_URL}:9443
        MINIO_LONGHORN_ACCESS_KEY: |-
          {{ .LONGHORN_MINIO_ACCESS_KEY }}
        MINIO_LONGHORN_SECRET_KEY: |-
          {{ .LONGHORN_MINIO_SECRET_KEY }}

        BACKBLAZE_URL: |-
          {{ .MINIO_BACKUP_BACKBLAZE_URL }}
        BACKBLAZE_LONGHORN_ACCESS_KEY: |-
          {{ .MINIO_BACKUP_BACKBLAZE_LONGHORN_ACCESS_KEY }}
        BACKBLAZE_LONGHORN_SECRET_KEY: |-
          {{ .MINIO_BACKUP_BACKBLAZE_LONGHORN_SECRET_KEY }}

        config.json: |
          {
            "version": "10",
            "aliases": {
              "b2-longhorn": {
                "url": "{{ .MINIO_BACKUP_BACKBLAZE_URL }}",
                "accessKey": "{{ .MINIO_BACKUP_BACKBLAZE_LONGHORN_ACCESS_KEY }}",
                "secretKey": "{{ .MINIO_BACKUP_BACKBLAZE_LONGHORN_SECRET_KEY }}",
                "api": "s3v4",
                "path": "auto"
              },
              "b2-postgres": {
                "url": "{{ .MINIO_BACKUP_BACKBLAZE_URL }}",
                "accessKey": "{{ .MINIO_BACKUP_BACKBLAZE_POSTGRES_ACCESS_KEY }}",
                "secretKey": "{{ .MINIO_BACKUP_BACKBLAZE_POSTGRES_SECRET_KEY }}",
                "api": "s3v4",
                "path": "auto"
              },
              "nas-longhorn": {
                "url": "https://${SECRET_MINIO_URL}:9443",
                "accessKey": "{{ .LONGHORN_MINIO_ACCESS_KEY }}",
                "secretKey": "{{ .LONGHORN_MINIO_SECRET_KEY }}",
                "api": "s3v4",
                "path": "auto"
              },
              "nas-postgres": {
                "url": "https://${SECRET_MINIO_URL}:9443",
                "accessKey": "{{ .POSTGRESQL_MINIO_ACCESS_KEY }}",
                "secretKey": "{{ .POSTGRESQL_MINIO_SECRET_KEY }}",
                "api": "s3v4",
                "path": "auto"
              }
            }
          }
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: longhorn
    - extract:
        key: minio-backup
    - extract:
        key: postgresql-minio
