apiVersion: v1
kind: Secret
metadata:
    name: vpn-config
    namespace: default
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:n/WUvJumVKXi0WWxoWsgMBUdO26yzJIvyap7xxMlWRqwYIz6sS7KtXAzHRA=,iv:N2jHaQjinlkU1SY19Ee22IURkee8Dzah92ZltYCULDc=,tag:jkk5BnBi5FEjc/v9Q9A8Hw==,type:str]
sops:
    age:
        - recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRmJGMlRWdEdicmQwdUNx
            YVJkWEdCSUh0QStnWXBYTk9Ud2JkYVlLUWlzCjZTNmxLVXZBbU9aTFhvQk1ZRWx1
            NWt1OXB2bjdTUUtTN1dWV0dXSVJ4cjgKLS0tIGpOWlY1MTlVMHZ2VjBYcnJxcjhI
            Q2wzVFhudkRYWmE2SFY2YzZnbCs2aUEKyzVpjBRXlDd2ib2M/h4q4l1CgOVbM0OO
            ioYgdGBOO2QRqrj5o0OJSEn7pR9VC3NoU1ztHCL5Lby9psQ+CUTV8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T12:09:37Z"
    mac: ENC[AES256_GCM,data:nruwmZ9nBfWqmgh8cwL5A13viA44DymHdv9dSI71xG81v+Bo17CsqlEfQ4uaK9QZFFZAWY1cYA4UbmuCvm0OZtcbARPlLfjfLG7QKtMGCefxch/l5amQtKimM1hH3O+D+TS+JBRZu03GobgjbDScRUTrfEXqGqwUrM724rJhoAc=,iv:6X3v4sZLUF/tliQz2LBk9LoX05QR3ADS3ov81RSBcas=,tag:C1DxYA/V1e9QReF3kJ+x9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
