---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  namespace: office
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    name: immich
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        JWT_SECRET: |-
          {{ .IMMICH_JWT_SECRET }}
        DB_DATABASE_NAME: |-
          {{ .IMMICH_POSTGRES_DATABASE_NAME }}
        DB_USERNAME: |-
          {{ .IMMICH_POSTGRES_DATABASE_USERNAME }}
        DB_PASSWORD: |-
          {{ .IMMICH_POSTGRES_DATABASE_PASSWORD }}
        OAUTH_CLIENT_ID: |-
          {{ .IMMICH_AUTHENTIK_CLIENT_ID }}
        OAUTH_CLIENT_SECRET: |-
          {{ .IMMICH_AUTHENTIK_CLIENT_SECRET }}
        # REDIS_PASSWORD: |-
        #   {{ .IMMICH_REDIS_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: immich
