---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-meta
  namespace: comms
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .MAUTRIX_META_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .MAUTRIX_META_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .MAUTRIX_META_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: mautrix-meta
    - extract:
        key: postgresql
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-meta-files
  namespace: comms
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: mautrix-meta-base-config
            items:
              - key: config.yaml
                templateAs: Values
        - target: Data
          configMap:
            name: mautrix-meta-base-config
            items:
              - key: registration.yaml
                templateAs: Values

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: mautrix-meta
