apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:4MMRPw+t1VWl42DvMkoLkNxHz3bvBoRmUW2keSQejXsYxiEtMQlruA==,iv:IQ9hHFN9bVvYHz8jNeUbGlmb0/zfsic11BBPlnjs1tM=,tag:nMaLwsmIz/3jmyRGFNbRJA==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:syhLJy5OnXuqZmzqWRg0QAhhY38C/vh/EImbEBJtgBOKf5d3FtPjA0ukFBPyttY9T870G9+54CBTi2gMY6+jPd7WRPLkvr/tOiMxXwZe0a0zcgfF/YqI/ThBhpva,iv:UxJTqEike1XxTrdQGDqFvhg9nqtO5niyQXogG4e4BzE=,tag:0Hj5x76Bxmx4CQhOZFiWYQ==,type:str]
    DOCKERHUB_USERNAME: ENC[AES256_GCM,data:OhLyfDE=,iv:YbxSDpJyUMVTfbm6pngnrd2wmIN1erdne5CTMqmyl1k=,tag:ccAUI5wbRmFnUOlMJuRxGQ==,type:str]
    DOCKERHUB_TOKEN: ENC[AES256_GCM,data:mFJZuNencyFXPP0EAF9xj2/gvV50aF6UJziBqfC/JUSVzpjq,iv:7NxXQJoKBE/PhxH5toC3JnL0sgmWqL9tqVddCc51e4Y=,tag:OmRvqL78fcLSp554ZPfGRw==,type:str]
sops:
    age:
        - recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaitqaStweEtxTzQ0aFdq
            TkQ2czFHUnpEcURUR1NMc1dwZWd2b0Z0QTJJCnhWc3NienBGSDk4WVVsMkwwbG1n
            K3lIS0lKeWN1K0tadDNxbWRLRHZzRFkKLS0tIGMraVJ2aDlwQVdNVWhnb3ZkaVRI
            anc4WE82VkpRSVBWd0pLcHJDUlUwaGMKLJW3SsX9uDxlZO+o1xTefuukqD7B/r7c
            pMpKu+66REYqb97DE1W76ERKsfz+UyzcuidG+pmaSO424Eb9Pqdb8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T14:07:02Z"
    mac: ENC[AES256_GCM,data:Q8+0BnNG2czFNJuwJKxWkdYPKQ6AZD018bp8KkH2/UwJ/DS2mnCfKdL4Vbn4l9HifDghpdF/JH0EAw7WNoyN23e9YmYCnYWBgf0hpq8NHT000bP6LThNpQHwznjhl1QwfsqPS29hmugHYLJbGu9K2h60XpapWmKrREePZGhrjFE=,iv:MZLq7DAT8Owjpf2A+A8WOVkpl+zlnJsdaPHCo4SdRbY=,tag:AErTLN+yD7nK1RXO+inBog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
