---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLUME_CLAIM:-${APP}}"
spec:
  accessModes:
    - "${VOLUME_ACCESSMODES:-ReadWriteOnce}"
  resources:
    requests:
      storage: "${VOLUME_CAPACITY:-1Gi}"
  storageClassName: "${VOLUME_STORAGECLASS:-longhorn}"
