---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - adguard/ks.yaml
  - atuin/ks.yaml
  - audiobookshelf/ks.yaml
  - bentopdf/ks.yaml
  - booklore/ks.yaml
  - calibre-web/ks.yaml
  - cloudnative-pg/ks.yaml
  - echo-server/ks.yaml
  - endurain/ks.yaml
  - flaresolverr/ks.yaml
  - garage/ks.yaml
  - homepage/ks.yaml
  - karakeep/ks.yaml
  - koffan/ks.yaml
  - miniflux/ks.yaml
  - omni-tools/ks.yaml
  - navidrome/ks.yaml
  - redlib/ks.yaml
  - shlink/ks.yaml
components:
  - ../../components/common
  - ../../components/cluster-vars
  - ../../components/limits
  - ../../components/forgejo-docker-creds
