---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PLUS_API_KEY: |-
          {{ .FRIGATE_PLUS_API_KEY }}
        FRIGATE_AMCREST_USERNAME: |-
          {{ .FRIGATE_AMCREST_USERNAME }}
        FRIGATE_AMCREST_PASSWORD: |-
          {{ .FRIGATE_AMCREST_PASSWORD }}
        FRIGATE_TAPO_USERNAME: |-
          {{ .FRIGATE_TAPO_USERNAME }}
        FRIGATE_TAPO_PASSWORD: |-
          {{ .FRIGATE_TAPO_PASSWORD }}
        FRIGATE_TAPO_CLOUD_PASSWORD: |-
          {{ .FRIGATE_TAPO_CLOUD_PASSWORD }}
        FRIGATE_IOT_DOMAIN: |-
          iot.wynning.tech
        FRIGATE_INTERNAL_DOMAIN: |-
          ${SECRET_INTERNAL_DOMAIN}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: frigate
