---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: registry.gitlab.com/fmd-foss/fmd-server
              tag: 0.16.0
            env:
              FMD_REMOTEIPHEADER: "X-Forwarded-For"
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/fmd-server/db

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "FMD"
          gethomepage.dev/description: "Find My Device"
          gethomepage.dev/group: "Applications"
          gethomepage.dev/icon: "fmd.png"
          gethomepage.dev/weight: "100"
          external-dns.alpha.kubernetes.io/hostname: "{{ .Release.Name }}.${SECRET_ROOT_DOMAIN}"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-towonel
            namespace: networking
          - name: envoy-internal
            namespace: networking
