---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  headers:
    earlyRequestHeaders:
      set:
        - name: X-Real-Ip
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
      #trustedCIDRs:
      #  - 10.44.0.0/16
  path:
    disableMergeSlashes: true
    escapedSlashesAction: KeepUnchanged
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    # Exclude envoy-towonel — it has its own ClientTrafficPolicy that adds PROXY protocol.
    - group: gateway.networking.k8s.io
      kind: Gateway
      matchExpressions:
        - key: network
          operator: NotIn
          values:
            - towonel
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
