---
apiVersion: v1
kind: LimitRange
metadata:
  name: ephemeral-storage-limit-ranges
spec:
  limits:
    - default:
        ephemeral-storage: "64Mi"
      defaultRequest:
        ephemeral-storage: "32Mi"
      type: Container
