---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: networking
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_API_TOKEN: |-
          {{ .EXTERNALDNS_CF_API_TOKEN }}
        MIKROTIK_BASEURL: |-
          {{ .EXTERNALDNS_MIKROTIK_BASEURL }}
        MIKROTIK_USERNAME: |-
          {{ .EXTERNALDNS_MIKROTIK_USERNAME }}
        MIKROTIK_PASSWORD: |-
          {{ .EXTERNALDNS_MIKROTIK_PASSWORD }}
        MIKROTIK_SKIP_TLS_VERIFY: |-
          {{ .EXTERNALDNS_MIKROTIK_SKIP_TLS_VERIFY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: external-dns
