---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxcd-operator
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        FLUXCD_OPERATOR_OIDC_CLIENT_SECRET: "{{ .FLUXCD_OPERATOR_OIDC_CLIENT_SECRET }}"
        FLUXCD_OPERATOR_OIDC_CLIENT_ID: "{{ .FLUXCD_OPERATOR_OIDC_CLIENT_ID }}"
        FLUXCD_OPERATOR_OIDC_ISSUER: "{{ .FLUXCD_OPERATOR_OIDC_ISSUER }}"
        FLUXCD_OPERATOR_BASE_URL: "https://{{ .FLUXCD_OPERATOR_HOSTNAME }}"
        FLUXCD_OPERATOR_HOSTNAME: "{{ .FLUXCD_OPERATOR_HOSTNAME }}"
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: fluxcd-operator
