---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-sync
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ORIGIN_URL: |-
          {{ .ADGUARD_ORIGIN_URL }}
        REPLICA1_URL: |-
          {{ .ADGUARD_REPLICA1_URL }}
        USERNAME: |-
          {{ .ADGUARD_USERNAME }}
        PASSWORD: |-
          {{ .ADGUARD_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: adguard
