---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # What TimeZone are your cluster located in
  CLUSTER_TZ: "America/Chicago"

  # Service static IPs
  SVC_ADGUARD1_ADDR: "192.168.1.5"
  SVC_ADGUARD2_ADDR: "192.168.1.6"
  SVC_K8S_GATEWAY_ADDR: "192.168.1.53"
  SVC_MOSQUITTO_ADDR: "192.168.1.202"
  SVC_MINECRAFT_ADDR: "192.168.1.203"
  SVC_MIMIC3_ADDR: "192.168.1.204"
  SVC_AUTHENTIK_LDAP_ADDR: "192.168.1.205"
  SVC_UNIFI_CONTROLLER_ADDR: "192.168.1.206"
  SVC_SYSLOG_ADDR: "192.168.1.207"
  SVC_MINIO_ADDR: "192.168.1.208"
  SVC_POSTGRESQL_ADDR: "192.168.1.209"
  SVC_PRIVATE_1_ADDR: "192.168.1.210"
  SVC_WYOMING_PIPER_ADDR: "192.168.1.211"
  SVC_WYOMING_WHISPER_ADDR: "192.168.1.212"
  SVC_COMPREFACE_ADDR: "192.168.1.213"
  SVC_WYOMING_OPENWAKEWORD_ADDR: "192.168.1.214"
  SVC_RABBITMQ_ADDR: "192.168.1.215"
  SVC_MINECRAFT_PROXY_ADDR: "192.168.1.216"
  SVC_MINECRAFT_ONE_ADDR: "192.168.1.217"
  SVC_IMMICH_POSTGRESQL_ADDR: "192.168.1.218"
  SVC_MUSIC_ASSISTANT_ADDR: "192.168.1.219"
  SVC_OLLAMA_ADDR: "192.168.1.220"
  SVC_SMTP_RELAY_ADDR: "192.168.1.221"
  SVC_ENVOY_GATEWAY_INTERNAL: "192.168.1.223"
  SVC_ENVOY_GATEWAY_TAILSCALE: "192.168.1.224"
  SVC_GARAGE_NAS_GATEWAY_ADDR: "192.168.1.225"
  SVC_WYOMING_PIPER_GLADOS_ADDR: "192.168.1.226"

  # Postgres
  SVC_POSTGRES_HOST: "postgres-rw.default.svc.cluster.local"
  SVC_POSTGRES_PORT: "5432"
