apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_ROOT_DOMAIN: ENC[AES256_GCM,data:5DC2GFZZ+NJgPQrR,iv:JB06+Vke4Ez9+EkET3JOKitiFA4bAUD74UUNgi1IJTo=,tag:eY2lOUQR0dOgao1Q/3uKMQ==,type:str]
    SECRET_ROOT_DOMAIN_REGEX_STUB: ENC[AES256_GCM,data:d/dm5HDONFWM4YDLYg==,iv:YMBDA+Ta7+IE96ELRGbpaLx8AOXXQ8C+Wlv5y82FVo8=,tag:1DiQGPDa3Xo0g4XB3Ocqaw==,type:str]
    SECRET_ROOT_DOMAIN_ESCAPED_REGEX_STUB: ENC[AES256_GCM,data:nk6F4d84gPxaXzRa6rc=,iv:BbyQN4UjIBy+XW/k0qAYoDiQhz2/sSdLHOpkdTUiyrY=,tag:yYFkIhgJis7bK4u7rgmTgA==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:McdaFTynQZozyVT4osKoyg==,iv:DvjsPo5nfYeR9i1DjY3ce1JFgSh8zk+ZxG1CaPA2y4w=,tag:cU2oy0YVSto6yEaW25W2iA==,type:str]
    SECRET_CORE_DOMAIN: ENC[AES256_GCM,data:gObFANvrg4yQlLc67tdyqgs=,iv:IHqmLT2Z3fxCoKepRPM+rY5jTnjqY8Os57vw2RDE3T0=,tag:uVUJkuQdvPuKG3Zb3BMXnQ==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:UCSJJFHTJ+66TZoRGydmBew1tQ==,iv:YUba1BU/jIVWAg8n6P3ibr9bHnyJwRKuUy73X9U9Aqc=,tag:bemcRLb7HzEC51QrgYtN4w==,type:str]
    SECRET_NAS_URL: ENC[AES256_GCM,data:XfD3JBKRlfUmQSHw3x9k2HpsDRoH,iv:3gvCkAg6zm1h3A0a7kD7CkBaE+c2qBRXrLjssgC+FcE=,tag:Fd0eFD8dKAQ3fYkwqC0pPg==,type:str]
    SECRET_MINIO_URL: ENC[AES256_GCM,data:zE5krWhLQyQfDKV5Z1RZ1ZVc9fASbkk=,iv:FMKkwI4i+ZiX7sBaxLSPSaSh48gIf3QyX1cKgeu25Ow=,tag:QLRdjlTm7oY8es8X9YtCPA==,type:str]
    SECRET_GARAGE_URL: ENC[AES256_GCM,data:6Zu28QzSf7P9XZoz4gcFEVEbNyg=,iv:55UoN3XyPuV1uNVlX7DpBOPYQIaoW7rP4ZrTYRUWwrg=,tag:G0XvwcCfpHutlNHpekc1ow==,type:str]
    #ENC[AES256_GCM,data:fTeR645Obg==,iv:vFQrX6KrwVXUp4Y9MToSLhQgL99/CdG5gNekBAOu/5c=,tag:Joq0NtFl30eq8xr42i8sBg==,type:comment]
    SECRET_GITHUB_USER: ENC[AES256_GCM,data:Ud5ybkazpIXx,iv:Yso5zqksGxKulcdGOPuyGtHS4uuCQsGRTXeKPc5Cc8s=,tag:4Z8HkVZWEJjfl+wfPEEMTg==,type:str]
    SECRET_GITHUB_REPO: ENC[AES256_GCM,data:MyxcueYTYpxGmQJDItBX9B+nz2EeRdwP2RaQ5MT54+X1kKAFfH9nD24=,iv:56BCqyO383M9WL//A0mCI27SUHqfErBgTR1df4OuGKA=,tag:e7CVNrCKdrmII4jAEAukwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV1Z1bVl5NlZwV3N2ZHhz
            UnV6d1M1WURGQkVibVdRT0NVb0ZJMWtzc1JNCkppbG9mWWFvbkZhMC9OMktNZzVR
            aVBSNGFPbmtSRVNoQm1Rd2dWWjRyL3cKLS0tIHY4dGdNeHVPWldxdk9hNUFJZnQx
            bi9zRkl2UEFld1JIQkhOWExSOHFKZ3cKL4Kw6Hu9KOMLK94GKDUyzjnY748geXNj
            UnrWB1Wa7J9VhARSx0+H+eLwiW8bDtTQLVg8Hziq+F0zuGQB5tgJLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zjgnh5c52xfue53fjsw7s5qyj5lqv9zj44rsk0rw7ywvs72xe3csfclpem
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T17:19:58Z"
    mac: ENC[AES256_GCM,data:G/ozzW1qA564HGq7HkBGisGvzLGU94rBogr9wVhY5NrGEZJcKQxDyTgjS6iZm2xIYbG6G4h3rwZuInygzTToq0ThXlwrXH1+YRVE59eKe3TwP6Z30AiIfdXtGuaPfHgMBrgeCwhgi4AYq+Dc/LvzFt7U/aY2+BkyRsZHpfXjYI8=,iv:+wU53h6ScX5rijVVxYzVZOzmbwYK5s5YZum9hNib38U=,tag:Y00APC0twSKmQCFaW8/hxg==,type:str]
    version: 3.13.1
