---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-garage
  namespace: monitoring
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GARAGE_ACCESS_KEY: |-
          {{ .TEMPO_GARAGE_ACCESS_KEY }}
        GARAGE_SECRET_KEY: |-
          {{ .TEMPO_GARAGE_SECRET_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: tempo
