---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # IDEON_DB_URI: |-
        #   postgresql://{{ .IDEON_POSTGRES_USERNAME }}:{{ .IDEON_POSTGRES_PASSWORD }}@${SVC_POSTGRES_HOST}:${SVC_POSTGRES_PORT}/{{ .IDEON_POSTGRES_DATABASE }}
        DB_NAME: |-
          {{ .IDEON_POSTGRES_DATABASE }}
        DB_USER: |-
          {{ .IDEON_POSTGRES_USERNAME }}
        DB_PASS: |-
          {{ .IDEON_POSTGRES_PASSWORD }}
        DB_PORT: "5432"
        DB_HOST: |-
          postgres.${SECRET_INTERNAL_DOMAIN}

        SECRET_KEY: |-
          {{ .IDEON_SECRET_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: ideon
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-init-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        INIT_POSTGRES_HOST: "${SVC_POSTGRES_HOST}"
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .POSTGRES_SUPERUSER_PASSWORD }}
        INIT_POSTGRES_DBNAME: |-
          {{ .IDEON_POSTGRES_DATABASE }}
        INIT_POSTGRES_USER: |-
          {{ .IDEON_POSTGRES_USERNAME }}
        INIT_POSTGRES_PASS: |-
          {{ .IDEON_POSTGRES_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: ideon
    - extract:
        key: postgresql
