---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DATABASE_PASSWORD: |-
          {{ .BOOKLORE_DATABASE_PASSWORD }}
        DATABASE_ROOT_PASSWORD: |-
          {{ .BOOKLORE_DATABASE_ROOT_PASSWORD }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: booklore
