---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        api-token: |-
          {{ .CERTMANAGER_CLOUDFLARE_API_TOKEN }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: cert-manager
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        tls.key: |-
          {{ .CERTMANAGER_LETSENCRYPT_TLS_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: cert-manager
---
# yaml-language-server: $schema=https://k8s-schemas.wynning.tech/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        tls.key: |-
          {{ .CERTMANAGER_LETSENCRYPT_STAGING_TLS_KEY }}

  refreshInterval: 15m
  dataFrom:
    - extract:
        key: cert-manager
