---
include:
  - model_config.yaml

general_settings:
  health_check_endpoint: /v1/health

  proxy_batch_write_at: 60
  database_connection_pool_limit: 10

  disable_spend_logs: false
  disable_error_logs: false

  background_health_checks: false
  health_check_interval: 300

  store_model_in_db: true
  store_prompts_in_spend_logs: true

  forward_client_headers_to_llm_api: true # REQUIRED: forwards the oauth token to Anthropic

litellm_settings:
  proxy_server: true
  request_timeout: 600
  json_logs: true
  # enable_preview_features: true
  redact_user_api_key_info: true
  turn_off_message_logging: false
  # set_verbose: true
  # drop_params: true

  success_callback:
    - "prometheus"
  failure_callback:
    - "prometheus"
  prometheus_adapter: true
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    ttl: 30
  drop_params: false
  num_retries: 2
  retry_after: 5
  set_verbose: false

# router:
#   - destination: vision_openai
#     if:
#       contains:
#         - "data:image"
#         - "image analysis"
#         - "describe this image"
#         - "photo"
#         - "diagram"

# router_settings:
#   fallbacks:
#     - vision_openai:  # ✅ Single key
#         - vision_anthropic
#         - vision_gemini
#         - vision_xai
#         - vision_bedrock
#     - general_openai:
#         - general_anthropic
#         - general_gemini
#         - general_xai
#     - code_fallback_together:
#         - code_fallback_groq
#     - code_fallback_groq:
#         - code_fallback_together

router_settings:
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
